Update radar_check.py
pyrevitlabs/pyRevit pull request #2419
Opened 2024-10-17 09:23 UTC by jmcouffin

reviewed tayO radar check

2024-10-17 09:28 UTC, jmcouffin commented
@tay0thman I reviewed more seriously your code, did quite a few edit for clarity and pep8 compliance
renamed lots of variables and methods.

- you need to review one last thing: pbt and psp aren't showing in display units
-  +nice to have, make X Y Z andangle when necessary in separate columns ;p

ref: #2418

2024-10-17 16:02 UTC, dosymep requested changes
@tay0thman, you need to check 
 - code formatting, lots of missing and extra spaces, 
 - non-pep8 variable naming,
 - the length of the lines should not be more [around 79 symbols](https://peps.python.org/pep-0008/#maximum-line-length)
 - shadows names

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> -        t = Transaction(doc, "Create 3D View")
I recommend using  `with` statement for any transaction, if is possible better use `revit.Transaction` [class](https://docs.pyrevitlabs.io/reference/pyrevit/revit/db/transaction/)

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        violating_CAD = []
Variable in function should be lowercase

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> -    def get_tempbbox(self, ToggleCAD, ToggleRVT, ToggleIFC, ToggleAll):
Argument name should be lowercase

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        view_3D_types = DB.FilteredElementCollector(doc).OfClass(DB.ViewFamilyType).WhereElementIsElementType().ToElements()
PEP 8: E501 line too long (124 > 120 characters)

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        ui_units = DB.UnitFormatUtils.Format(units=doc.GetUnits(), unitType=DB.UnitType.UT_Length, value=distance, maxAccuracy=False, forEditing=False)
It is advisable to make the code formatting similar in the same places

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
>      def setUp(self, doc, output):
Shadows name 'doc' from outer scope

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
>                  print(output.linkify(y.Id)+ str(y.Name)+ " - Is part of design option - "+ str(y.DesignOption.Name) )
missing spaces, formatting is messed up

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +                    if check_bounding_box(bbox, INTERNAL_ORIGIN, 52800) == 0:
magic number, needs create constant or comment with unit of measurement

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +    # __________________________________________check the distnaces of base and survey points
misspelling `distnaces`

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +    tabledata = [['InternaL Origin Coordinates', str(INTERNAL_ORIGIN)],
misspelling `InternaL`

2024-10-17 16:02 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
>          sys.exit()
I think better to use `script.exit()` [docs](https://docs.pyrevitlabs.io/reference/pyrevit/script/#pyrevit.script.exit)

2024-10-17 16:58 UTC, tay0thman commented
Thank you @dosymep for your thorough review and feedback, good to know how important these items are and will change the code to reflect these recommendations very shortly.

Thanks again

2024-10-17 20:41 UTC, tay0thman approved these changes
These Edits makes sense, I am approving them and testing on my scenarios using multiple models. I'll carry all necessary edits to meet with the additional comments.

2024-10-17 21:28 UTC, tay0thman approved these changes

2024-10-18 05:29 UTC, tay0thman commented on extensions/pyRevitTools.extension/checks/radar_check.py
> -        t = Transaction(doc, "Create 3D View")
I just learned the wrapped dry-transaction, pretty cool!

2024-10-18 05:31 UTC, tay0thman commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        violating_CAD = []
done!

2024-10-18 05:31 UTC, tay0thman commented on extensions/pyRevitTools.extension/checks/radar_check.py
> -    def get_tempbbox(self, ToggleCAD, ToggleRVT, ToggleIFC, ToggleAll):
done!

2024-10-18 05:33 UTC, tay0thman commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        view_3D_types = DB.FilteredElementCollector(doc).OfClass(DB.ViewFamilyType).WhereElementIsElementType().ToElements()
I am updating the script to limit my lines to 80 characters. I am exceeding these for few lines but will make sure it is less than 120

2024-10-18 06:15 UTC, dosymep commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        view_3D_types = DB.FilteredElementCollector(doc).OfClass(DB.ViewFamilyType).WhereElementIsElementType().ToElements()
I use [pyCharm](https://www.jetbrains.com/pycharm), it has a vertical line and hints about it, but I think in vs code there are also the same settings or plugins for tracking coding style

<img width="500" alt="image" src="https://github.com/user-attachments/assets/66513a15-4103-4a3e-872f-72c0d5c6cb3f">

2024-10-18 16:53 UTC, tay0thman commented
Hello @jmcouffin  and @dosymep  I carried the updates and generated a new pull request.

2024-10-18 17:14 UTC, tay0thman commented on extensions/pyRevitTools.extension/checks/radar_check.py
> +        view_3D_types = DB.FilteredElementCollector(doc).OfClass(DB.ViewFamilyType).WhereElementIsElementType().ToElements()
yup, I was able to achieve the same with vscode :)

2024-10-21 09:06 UTC, closed without merging