color splasher update branch
pyrevitlabs/pyRevit pull request #2457
Opened 2024-11-16 10:56 UTC by jmcouffin

update from @jaimeAlonso porting to pyRevit

2024-12-01 08:17 UTC, sanzoghenzo requested changes
Just went through the first 300 lines, I see if I have some time to check the rest...

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> -from System.Collections.Generic import *
pyrevit.framework already adds these references, and Forms is then imported in pyrevit init module, so

```
from pyrevit.Forms import *
from pyrevit.framework.Drawing import *
from pyrevit.framework import Array
from pyrevit.framework.System import Environment, String
```

`System.Data` is not there, so it is the only one that needs to be added to the clr

(As a pure pythonista I would add that the wildcard imports are not recommended, but I get that in the context of pyRevit and IronPython it's closer to the c# way and we can tolerate them)

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>              if view != 0:
I know this is not inside your changes, but can we invert the if condition to de-indent the code?

```python
if not view:
   return
```

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                          break
```suggestion
                solidFillId = next(
                    (pat.Id for pat in fElementCollector if pat.GetFillPattern().IsSolidFill), 
                    None,
                )
```

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                      else:
I would invert these if conditions to have the shortest branch first, and condense nested if/else conditions with `and` and `elif`

```suggestion
                    # In case of rooms, spaces and areas. Check Color scheme is applied and if not
                    if get_elementid_value(sel_cat._cat.Id) not in (int(DB.BuiltInCategory.OST_Rooms), int(DB.BuiltInCategory.OST_MEPSpaces), int(DB.BuiltInCategory.OST_Areas)):
                        wndw._txtBlock5.Visible = False
                    elif version <= 2021:
                        wndw._txtBlock5.Visible = True
                    elif str(wndw.crt_view.GetColorFillSchemeId(sel_cat._cat.Id)) == "-1":
                        fColorScheme = DB.FilteredElementCollector(new_doc).OfClass(DB.BuiltInCategoryFillScheme).ToElements()
                        for sch in fColorScheme:
                            if sch.CategoryId == sel_cat._cat.Id and sch.GetEntries():
                                wndw.crt_view.SetColorFillSchemeId(sel_cat._cat.Id, sch.Id)
                                break
```

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +                                fColorScheme = DB.FilteredElementCollector(new_doc).OfClass(DB.BuiltInCategoryFillScheme).ToElements()
Typo here, I believe it should be `DB.ColorFillScheme` (or use of category `DB.BuiltInCategory.OST_ColorFillSchema`)

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +                        for id in wndw._listBox2.Items[indx]['Value']._eleId:
Not tested with Forms controls Items, but can this just be

```
from item in wndw._listBox2.Items:
    value = item["Value"]
```

so we avoid the repetion of accessing the list by index every time?

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +                        if len(filters) != 0:
Useless check, remove

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +            if len(legends) > 0:
invert the if condition as suggested above, but this method has another big problem, it is really huge!
could this branch be extracted into a method/function, and maybe split into smaller ones?

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                          if i == 1000:
Turn it into a `for i in range(1000)` loop, we break out of it once a good name is found anyway

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                              if ty.ForegroundPatternColor.IsValid:
these can be made into a single `if` condition with `and` (and maybe turned into a `is_valid_solid_fill` function or something like that)

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                  if len(filled_type) == 0 and len(all_types) > 0:
```suggestion
                if not filled_type all_types:
```

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                                  break
same as above, use for loop

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                                  break
use for loop

2024-12-01 08:17 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +                    if index != 0:
maybe `for index, vw_item in enumerate(wndw._listBox2.Items)` would work the same?

2024-12-01 08:51 UTC, jmcouffin commented
Thanks @sanzoghenzo, keep them coming.
I was in the middle of a code cleaning and huge overall. I know I will have some time (in the train) next week to keep going.

End goal 
I would like to make it a wpf/xaml UI instead of this looooong winforms.

2024-12-01 21:39 UTC, sanzoghenzo requested changes
I didn't get much into the details, just skimmed though what I could spot quickly, but I think I already gave you work to do :sweat_smile:

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>      if para.HasValue:
invert if and return "None" immediately, so you can skip the `else` and de-indent everything

Also, since `value` is just returned at the end of the function, you can just return directly to then remove the `else` and turn `elif`s into `if`s

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                          value = "False"
```suggestion
                    return "True" if para.AsInteger() == 1 else "False"
```

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                          value = "False"
same as above

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                      match[0]._eleId.Add(ele.Id)
since we use only the first item of match, we can use next

```suggestion
                match = next((x for x in list_values if x._value == valor), None)
                if match:
                    match._eleId.Add(ele.Id)
```

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                          if len(match) == 0:
```suggestion
                        if not any (x._n1 == r and x._n2 == g and x._n3 == b for x in list_values):
```

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +        list_values.Remove(copy[0])
use `next` here also

```
        copy = next((x for x in list_values if x._value == "None"), None)
        if copy:
            list_values.remove(copy)
```

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +        if ele.Category is not None:
invert if and de-indent the rest

```suggestion
        if ele.Category is None:
            continue
```

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>                  if not any(x._intId == current_int_cat_id for x in list_cat):
same as above

```suggestion
            if current_int_cat_id in cat_exc or current_int_cat_id >= -1 or any(x._intId == current_int_cat_id for x in list_cat):
                continue
```

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +        self._spr_top = System.Windows.Forms.Label()
this is valid for almost each line below this: if you change the import as suggested at the beginning, there you can just use `Forms.XXX` and `Drawing.XXX`

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
this change here is not needed, between class methods there should be only one white line

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
revert

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>      def Button6Click(self, sender, e):
revert

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
revert

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
remove one line

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +                b = 0
use

```
a = max(startColor.A + int(aStep * index) - 1, 0)
```

and so on

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
revert

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
revert

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +
revert

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
>          if sender.SelectedIndex != -1:
invert if and exit early

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +        if sel_cat is not None and sel_cat != 0:
invert if and exit early

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +        if isfile(path):
invert if and exit early

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +                                    item['Value']._colour = System.Drawing.Color.FromArgb(r,g,b)
extract out to a function and reuse it at line 1167

2024-12-01 21:39 UTC, sanzoghenzo commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +    cat_excluded = [int(DB.BuiltInCategory.OST_RoomSeparationLines), int(DB.BuiltInCategory.OST_Cameras), int(DB.BuiltInCategory.OST_CurtainGrids), int(DB.BuiltInCategory.OST_Elev), int(DB.BuiltInCat
it is most performant to use a set (`{}`) instead of a list to check for existence/membership

2024-12-29 21:20 UTC, jmcouffin commented on extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
> +        list_values.Remove(copy[0])
does not work in my case, nevermind.

`IronPython.Runtime.Exceptions.TypeErrorException: object of type 'NoneType' has no len()`

2024-12-29 22:08 UTC, jmcouffin reviewed
reviewed, will commit separately

2024-12-29 22:25 UTC, merged