Rewrite pyRevit configurations
pyrevitlabs/pyRevit pull request #2482
Opened 2024-12-18 11:17 UTC by dosymep

- added config abstraction
- added config overrides (need testing and design the logic of work)
- replace ini lib to `ini-parser`
- added json configuration
- added yaml configuration (doesn't work I need to figure out the parser library)

I think in general a start has been made, it remains to rewrite the logic of the config in python

2024-12-18 11:23 UTC, dosymep commented
@jmcouffin @sanzoghenzo how to trigger github action?

2024-12-18 11:31 UTC, jmcouffin commented
I just launched it.
15min+ to go

I won't be able to review just now, best I can do is install the wip that will be created

2024-12-19 18:18 UTC, sanzoghenzo requested changes
Awesome job @dosymep !

I didn't run the code, only skimmed through, and only found some grammar to fix (`ShouldThrows -> ShouldTrow`).

Do you think it would be worth creating separate repo(s) and nuget package(s) for this feature (just to start the transition to a better code structure)?

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Yaml.Tests/YamlConfigurationUnitTests.cs
> +    public void CreateIniConfiguration_ShouldThrowsException()
```suggestion
    public void CreateIniConfiguration_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Yaml.Tests/YamlConfigurationUnitTests.cs
> +    public void CreateIniConfigurationByBuilder_ShouldThrowsException()
```suggestion
    public void CreateIniConfigurationByBuilder_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Yaml.Tests/YamlConfigurationUnitTests.cs
> +    public void CreateIniConfigurationByNullBuilder_ShouldThrowsException()
```suggestion
    public void CreateIniConfigurationByNullBuilder_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Tests/ConfigurationTests.cs
> +    public void RemoveExitsValue_ShouldReturnsTrue()
```suggestion
    public void RemoveExitsValue_ShouldReturnTrue()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Tests/ConfigurationTests.cs
> +    public void GetValueOrDefault_ShouldReturnsDefaultValue()
```suggestion
    public void GetValueOrDefault_ShouldReturnDefaultValue()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Tests/ConfigurationTests.cs
> +    public void GetValueOrDefault_ShouldReturnsSameValue()
```suggestion
    public void GetValueOrDefault_ShouldReturnSameValue()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Tests/ConfigurationTests.cs
> +    public void NewCreateValue_ShouldReturnsSameValue()
```suggestion
    public void NewCreateValue_ShouldReturnSameValue()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Json.Tests/JsonConfigurationUnitTests.cs
> +    public void CreateIniConfigurationByNullBuilder_ShouldThrowsException()
```suggestion
    public void CreateIniConfigurationByNullBuilder_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Json.Tests/JsonConfigurationUnitTests.cs
> +    public void CreateIniConfigurationByBuilder_ShouldThrowsException()
```suggestion
    public void CreateIniConfigurationByBuilder_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Json.Tests/JsonConfigurationUnitTests.cs
> +    public void CreateIniConfiguration_ShouldThrowsException()
```suggestion
    public void CreateIniConfiguration_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Ini.Tests/IniConfigurationUnitTests.cs
> +    public void CreateIniConfigurationByNullBuilder_ShouldThrowsException()
```suggestion
    public void CreateIniConfigurationByNullBuilder_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Ini.Tests/IniConfigurationUnitTests.cs
> +    public void CreateIniConfigurationByBuilder_ShouldThrowsException()
```suggestion
    public void CreateIniConfigurationByBuilder_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/tests/pyRevitLabs.Configurations.Ini.Tests/IniConfigurationUnitTests.cs
> +    public void CreateIniConfiguration_ShouldThrowsException()
```suggestion
    public void CreateIniConfiguration_ShouldThrowException()
```

2024-12-19 18:18 UTC, sanzoghenzo commented on dev/pyRevitLabs/pyRevitLabs.PyRevit/PyRevitConfigs.cs
> +                            + $"or it is not your user account.");
```suggestion
                            + "or it is not your user account.");
```

2024-12-20 11:38 UTC, dosymep commented
> creating separate repo(s) and nuget package(s)
it won't work, we have dependencies on this repo, at the moment I still don't know how to do this :(

2024-12-20 12:32 UTC, sanzoghenzo commented
> > creating separate repo(s) and nuget package(s)
> 
> it won't work, we have dependencies on this repo, at the moment I still don't know how to do this :(

Fair enough, let's worry about that later then!

2024-12-26 08:42 UTC, sanzoghenzo commented
HI @dosymep,

The attributes solution is really nice!

Just one question, out of curiosity: why did you turn `GetValueImpl` into a non-generic method? wouldn't it work the same?

2024-12-27 12:22 UTC, dosymep commented
@sanzoghenzo 
I updated internal API, to get values from reflection

https://github.com/pyrevitlabs/pyRevit/pull/2482/files#diff-3e1f8a1b067a136ccc1a3c88ee1bf54a3f0dac93b46c9ba785d9e86096f5e7c6R152

2024-12-27 13:53 UTC, sanzoghenzo commented
> @sanzoghenzo I updated internal API, to get values from reflection
> 
> https://github.com/pyrevitlabs/pyRevit/pull/2482/files#diff-3e1f8a1b067a136ccc1a3c88ee1bf54a3f0dac93b46c9ba785d9e86096f5e7c6R152

Yes I saw that, i should have asked you "why can't you use generics with reflection?" but it doesn't matter as long as it works! :wink:  it is just something I have to learn about .net...

2024-12-27 13:55 UTC, dosymep commented
> Yes I saw that, i should have asked you "why can't you use generics with reflection?" but it doesn't matter as long as it works! 😉 it is just something I have to learn about .net...

because when I ask for a type from reflections, they return me an object of the `Type`. I can't pass it as a generic parameter

2024-12-27 14:16 UTC, dosymep commented
remaining
- write tests
- write code in python

2024-12-27 15:12 UTC, sanzoghenzo commented
As for the python side, do you think that we can directly use these new classes in the `userconfig.py`?

Are user-defined sections and keys supported?

2024-12-27 16:54 UTC, dosymep commented
> As for the python side, do you think that we can directly use these new classes in the `userconfig.py`?
> Are user-defined sections and keys supported?
1 yep
2 yep
but need check :D

2026-01-10 16:57 UTC, jmcouffin commented
Should we keep this one opened? @dosymep

2026-01-12 07:55 UTC, dosymep commented
> Should we keep this one opened? @dosymep

Let it be, maybe I'll continue someday, or someone else will

2026-02-21 14:18 UTC, jmcouffin commented
@OnePowerUser88 ☝️

2026-02-25 12:47 UTC, OnePowerUser88 commented
I've been testing the branch locally with Revit 2026 (build + smoke test, then fixing runtime issues so it runs). Here's a short summary and the list of changes I have made on top of the branch to get everything working. Sharing for discussion, as I'm not shure how to contribute to a PR on GH, but can contribute my code if someone can give me guidance (I assume I can make a PR to the feature/configuration branch?).

## Summary

The new C# config stack (typed sections, INI provider, `GetValueOrDefault` / `SaveSection`) is in place and the INI file is read/written correctly. Python uses the C# layer; no revert to the old Python-only config. I only fixed bugs and added a small compatibility layer so existing code and extensions that still call `user_config.core.get_option()` keep working.

## List of what I fixed locally (for testing)

### 1. `pyrevitlib/pyrevit/coreutils/configparser.py`

- **get_option:** Use `GetValueOrDefault(section, option, "")` then `json.loads(value)`; handle empty.
- **__setattr__:** Skip `__section_name` and `__configuration` (use `object.__setattr__` for those) so `__init__` can set them and the rest goes through `set_option`.
- **Subsections:** Use `__configuration` / `__section_name`; `add_subsection` / `get_subsection` return correct types and `None` when not found.

### 2. `pyrevitlib/pyrevit/userconfig.py`

- Use `getattr(EXEC_PARAMS, 'doc_mode', False)` where `doc_mode` is read (not present on this branch).
- **User extension folders:** Read from `self.core.UserExtensions` (and `(self.core.UserExtensions or [])`); write with `framework.List[str](...)` so C# gets a `List<string>`.
- **_SectionCompatWrapper:** Wrapper around Core/Routes/Telemetry that exposes `get_option` / `set_option` and forwards other attributes to the C# section (so extensions and Settings UI keep working).
- **__setattr__** on the wrapper: Forward property sets to the underlying C# section so Settings changes apply to the real section.
- **save_changes():** Call `SaveSection` with `config_service.Core`, `config_service.Routes`, `config_service.Telemetry` (not the Python wrappers) so the C# side gets the right type and the INI is updated.

### 3. `dev/pyRevitLabs/pyRevitLabs.Configurations.Ini/IniConfiguration.cs`

- For requested type `string`, return the raw value (no `JsonConvert.DeserializeObject`), so Python can `json.loads()` it (handles arrays and other JSON).
- Hex integer parsing for legacy INI (e.g. `0x0`).
- net48: Use `Substring(1, valueToParse.Length - 2)` instead of `[1..^1]`.

### 4. `dev/pyRevitLabs/pyRevitLabs.PyRevit/pyRevitLabs.PyRevit.csproj`

- **DeployDependencies:** Copy `INIFileParser.dll` to the output so the INI provider loads.

### 5. `pyrevitlib/pyrevit/runtime/__init__.py`

- Resolve runtime assembly path: try `BIN_DIR` first, then `BIN_DIR/engines/<EngineVersion>/` so the Runtime DLL is found when it's only under `engines` (e.g. after building the Runtime solution).

### 6. `pyrevitlib/pyrevit/revit/tabs.py`

- **_get_tabstyle / _get_family_tabstyle:** Coerce index to `int(...)` (config can return string).
- **hex_to_brush:** Defensive handling (string, default brush) so bad/malformed config doesn't crash.
- **_get_tab_orderrules:** Treat `tab_colors` as list only when `isinstance(raw, list)`.
- **_get_tab_filterrules:** Treat `tab_filtercolors` as dict only when `isinstance(tab_filtercolors, dict)`.

### 7. `dev/pyRevitLabs/tests/.../ConfigurationServiceFixture.cs`

- Mock: Implement `GetSectionNames()` and `GetSectionOptionNames(string)` so the solution builds.

---

After these changes, Settings persist correctly to `pyRevit_config.ini` based on my testing (it might have before, but pulling the clean PR and building it was not working out-of-the-box for me). 
I hope this testing is aligned with the intent of the PR?

**Question:** What other features or fixes are planned for this PR that I could help test or look into? For example:
- Config overrides (design and testing of precedence/order)?
- YAML configuration (parser library and integration)?
- Remaining Python config logic to rewrite onto the C# layer?
- JSON configuration (same level of testing/integration as INI)?
- INI file locking / multi-process behaviour (#2512)?
- Other?

2026-06-22 22:34 UTC, ChrisCrosley commented
Any objections to me taking a swing at bringing this up to date with develop?

2026-06-23 07:32 UTC, jmcouffin commented
> Any objections to me taking a swing at bringing this up to date with develop?

I don't have any, @dosymep you?

a few notes though, I'd rather have a draft PR with no code changes and a clear plan that @dosymep or others can review before deeep diving. And there is a significant amount of drift between now and the start of this PR, 1 and a half year ago.

2026-06-23 12:50 UTC, dosymep commented
I don't mind, but maybe everything there is already very outdated

2026-09-15 20:43 UTC, closed without merging